name: deborasmail
favicon: null
layout_spectrum: 0.25918
typography_spectrum: 0.72959
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fcfcfc'
    - '#858585'
    - '#c5c5c5'
    - '#262626'
  brandStrength: 1
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0.75
purpose:
  - name: engagement
    item: null
    url: null
