name: deborasmail
favicon: null
layout_spectrum: 0.74617
typography_spectrum: 0.2529538
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fcfcfc'
    - '#858585'
    - '#c5c5c5'
    - '#262626'
  brandStrength: 0
  lightness: 1
  saturation: 0
  rhythmicContrast: 0
purpose:
  - name: engagement
    url: null
    item: null
